---
title: 'Two Sided Statistical Test'
author: 
  - Michael Hagmann ^[hagmann@cl.uni-heidelberg.de]
  - Stefan Riezler
  
date: ""

output:
  pdf_document:
    latex_engine: xelatex
  bookdown::pdf_book: default
    
urlcolor: blue
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      cache.lazy = FALSE,
                      dev = c("svglite", "pdf", "png"),
                      dpi = 300,
                      fig.path = 'figures/',
                      fig.keep = "high")

#added from: https://github.com/yihui/knitr-examples/blob/master/077-wrap-output.Rmd
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

```

```{r load libs, inclue=FALSE}
library(tidyverse)
library(cowplot)
library(ggpattern)
library(latex2exp)
```

```{r, include=FALSE}
alpha <- .05
max_distance <- 12
d_obs <- 9.5

upper_quantile <- qchisq(1 - alpha, df = 3)


upper_poly <- 
  tibble(x = seq(upper_quantile, max_distance, length.out = 100)) %>%
  mutate(density = dchisq(x, df = 3)) %>%
  bind_rows(tibble_row(x = upper_quantile, density = 0), 
            ., 
            tibble_row(x = max_distance, density = 0))


p_poly <- 
  tibble(x = seq(d_obs, max_distance, length.out = 100)) %>%
  mutate(density = dchisq(x, df = 3)) %>%
  bind_rows(tibble_row(x = d_obs, density = 0), 
            ., 
            tibble_row(x = max_distance, density = 0))


gap_poly <- 
  tibble(x = seq(upper_quantile, d_obs, length.out = 100)) %>%
  mutate(density = dchisq(x, df = 3)) %>%
  bind_rows(tibble_row(x = upper_quantile, density = 0), 
            ., 
            tibble_row(x = d_obs, density = 0))


rug_data <- 
  tibble(x        = seq(0, max_distance, length.out = 500),
         decision = ifelse(x <= upper_quantile,
                           "accept H\u2080",
                           "reject H\u2080"))
label_data <-
  tibble(x_start = d_obs + .5,
         y_start = dchisq(x_start, df = 3) / 2,
         x_end   = d_obs + 1,
         y_end   = dchisq(x_start, df = 3) * 5,
         label   = TeX(r"(P_{H_0}(W > w))", output="expression"))
```




```{r lrt_sided_test, echo=FALSE, fig.height = 4.5, fig.width = 7.29, fig.align = "center"}

#colours <- c("blue3", "goldenrod1", "red3")

colours <-c(rgb(0, 0, 205, max = 255, alpha = 125),
            rgb(255, 193, 37, max = 255, alpha = 125),
            rgb(205, 0, 0, max = 255, alpha = 255),
            rgb(0, 0, 0, max = 255, alpha = 0))
  
ggplot() +
  theme_minimal_grid(font_size = 12) +
  scale_colour_manual(values = c("accept H\u2080" = colours[1],
                                 "reject H\u2080" = colours[2])) +
  geom_polygon(data = p_poly,
               aes(x = x, y = density),
               colour = "white",
               fill   = colours[3]) +
  geom_polygon(data = gap_poly,
               aes(x = x, y = density),
               colour = "white",
               fill = colours[2]) +
  geom_polygon_pattern(data = upper_poly,
                       aes(x = x, y = density),
                       colour = "white",
                       fill   = colours[4],
                       pattern = "circle",
                       pattern_fill = colours[2],
                       pattern_angle = -45,
                       pattern_alpha = .7,
                       pattern_density =  0.7,
                       pattern_spacing = 0.01) +
  geom_rug(data = rug_data,
           aes(x = x, colour = decision)) +
  geom_vline(aes(xintercept = c(upper_quantile, d_obs)), 
             linetype = "dotted") +
  stat_function(data = tibble(x = c(0, max_distance)), 
                aes(x),
                n = 2000,
                fun = dchisq, 
                args = list(df = 3)) +
  geom_text(data = label_data,
            aes(x = x_end , y = y_end, label = label),
            hjust = 0,
            vjust = .25,
            parse = TRUE) +
  geom_segment(data = label_data,
               aes(x = x_start, y = y_start, xend = x_end, yend = y_end),
               alpha = .6) +
  xlab("test statistic W value") +
  ylab("distribution of test statistic W under H\u2080") +
  labs(colour = "test decision") +
  theme(legend.position = c(.82, .85)) +
  scale_y_continuous(breaks = NULL) +
  scale_x_continuous(breaks = c(upper_quantile, d_obs),
                     labels = c("(1-\u03B1)-quantile", "w"))
```