---
title: 'Two Sided Statistical Test'
author: 
  - Michael Hagmann ^[hagmann@cl.uni-heidelberg.de]
  - Stefan Riezler
  
date: ""

output:
  pdf_document:
    latex_engine: xelatex
  bookdown::pdf_book: default
    
urlcolor: blue
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      cache.lazy = FALSE,
                      dev = c("svglite", "pdf", "png"),
                      dpi = 300,
                      fig.path = 'figures/',
                      fig.keep = "high")

#added from: https://github.com/yihui/knitr-examples/blob/master/077-wrap-output.Rmd
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})

```

```{r load libs, inclue=FALSE}
library(tidyverse)
library(cowplot)
library(ggpattern)
library(ggrepel)
library(viridis)
```

```{r, include=FALSE}
alpha <- .05
max_distance <- 3

lower_quantile <- qnorm(alpha / 2, mean = 0, sd = 1)
upper_quantile <- qnorm(1 - alpha / 2, mean = 0, sd = 1)

lower_poly <- 
  tibble(x = seq(-max_distance, lower_quantile, length.out = 100)) %>%
  mutate(density = dnorm(x, mean = 0, sd = 1)) %>%
  bind_rows(tibble_row(x = -max_distance, density = 0), 
            ., 
            tibble_row(x = lower_quantile, density = 0))

upper_poly <- 
  tibble(x = seq(upper_quantile, max_distance, length.out = 100)) %>%
  mutate(density = dnorm(x, mean = 0, sd = 1)) %>%
  bind_rows(tibble_row(x = upper_quantile, density = 0), 
            ., 
            tibble_row(x = max_distance, density = 0))

rug_data <- 
  tibble(x        = seq(-max_distance, max_distance, length.out = 500),
         decision = ifelse(between(x, lower_quantile, upper_quantile),
                           "accept H\u2080",
                           "reject H\u2080"))
label_data <-
  tibble(x_start = c(lower_quantile - .2,
                   upper_quantile + .2),
         y_start     = dnorm(x_start, mean = 0, sd =1) / 2,
         x_end   = c(lower_quantile - .6,
                   upper_quantile + .6),
         y_end     = dnorm(x_end, mean = 0, sd =1) * 5,
         label = c("\u03B1/2 ", " \u03B1/2"))
```

```{r two_sided_test, echo=FALSE, fig.height = 4.5, fig.width = 7.29, fig.align = "center"}

#colours <- c("blue3", "goldenrod1")

colours <-c(rgb(0, 0, 205, max = 255, alpha = 125),
            rgb(255, 193, 37, max = 255, alpha = 125))
  
ggplot() +
  theme_minimal_grid(font_size = 12) +
  scale_colour_manual(values = c("accept H\u2080" = colours[1],
                                 "reject H\u2080" = colours[2])) +
  geom_polygon_pattern(data = lower_poly,
                       aes(x = x, y = density),
                       colour = "white",
                       fill   = colours[2],
                       pattern = "circle",
                       pattern_fill = colours[2],
                       pattern_alpha = .7,
                       pattern_density =  0.7,
                       pattern_spacing = 0.01) +
  geom_polygon_pattern(data = upper_poly,
                       aes(x = x, y = density),
                       colour = "white",
                       fill   = colours[2],
                       pattern = "circle",
                       pattern_fill = colours[2],
                       pattern_angle = -45,
                       pattern_alpha = .7,
                       pattern_density =  0.7,
                       pattern_spacing = 0.01) +
  geom_rug(data = rug_data,
           aes(x = x, colour = decision)) +
  geom_vline(aes(xintercept = c(lower_quantile, upper_quantile)), 
             linetype = "dotted") +
  stat_function(data = data.frame(x = c(-1, 1) * max_distance), 
                aes(x),
                n = 2000,
                fun = dnorm, 
                args = list(mean = 0, sd = 1)) + 
  geom_text(data = label_data,
            aes(x = x_end , y = y_end, label = label, hjust = c(1,0)),
            vjust = .25) +
  geom_segment(data = label_data,
               aes(x = x_start, y = y_start, xend = x_end, yend = y_end),
               alpha = .6) +
  xlab("test statistic value") +
  ylab("distribution of test statistic under H\u2080") +
  labs(colour = "test decision") +
  theme(legend.position = c(.82, .85)) +
  scale_y_continuous(breaks = NULL) +
  scale_x_continuous(breaks = c(lower_quantile, upper_quantile),
                     labels = c("(\u03B1/2)-quantile", "(1-\u03B1/2)-quantile"))
```

