---
title: 'Using LMEMs to Analyse Model Performance Beyond Mean Measures'
author: 
  - Michael Hagmann^[hagmann@cl.uni-heidelberg.de]
  - Stefan Riezler
  
date: '`r format(Sys.Date(), "%B %d, %Y")`'

output:
  bookdown::pdf_book: default

urlcolor: blue

header-includes:
  - \usepackage{mathtools}
  - \usepackage{amsmath}
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      cache.lazy = FALSE,
                      dev = c("svglite", "pdf", "png"),
                      dpi = 300,
                      fig.path = 'figures/',
                      fig.keep = "high")


#added from: https://github.com/yihui/knitr-examples/blob/master/077-wrap-output.Rmd
library(knitr)
hook_output = knit_hooks$get('output')
knit_hooks$set(output = function(x, options) {
  # this hook is used only when the linewidth option is not NULL
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    # any lines wider than n should be wrapped
    if (any(nchar(x) > n)) x = strwrap(x, width = n)
    x = paste(x, collapse = '\n')
  }
  hook_output(x, options)
})
```

```{r, message=FALSE, include=FALSE}
library(tidyverse) # A collection of packages for data science. More about it on 
                   # www.tidyverse.com
library(magrittr)  # A package that provides pipe operators like %>%
library(lme4)      # A package 
library(glue)      # A package that provides interpolated string functions.
library(latex2exp) # A package that converts latex to plotmath expressions.library(lmerTest)
library(lmerTest)  # A package that improves inference for LMEM.
library(emmeans)   # A package that allows to conduct post-hoc tests.
library(parameters)   
```

```{r read data, message=FALSE}
#this data set contains replicates for different seeds 
data_ter <- 
  readRDS("data/data_ter.rds")

summary(data_ter)
```

## A traditional way of analyzing system performance
```{r avaerage over replicates (seed)}
#for a traditional analysis one has to average over replicates
data_ter_mean <- 
  data_ter %>%
  select(-replication) %>%
  group_by(across(!ter)) %>%
  summarize(ter = mean(ter))
```


```{r kreutzer_sig_fig1, echo=FALSE, fig.height = 3.9, fig.width = 4.1, fig.align = "center"}
ggplot(data = data_ter_mean) +
  theme_bw() +
  theme(legend.position = "none") +
  xlab("") +
  ylab("TER Score") +
  geom_boxplot(aes(x = system, y = ter, fill = system), alpha = .3)
```


```{r summarize mean system performance, message=FALSE}
data_ter_mean %>%
  group_by(system) %>%
  summarise(mean_ter = mean(ter)) %>%
  mutate(baseline_difference = mean_ter - mean_ter[1])
```



```{r conduct model based ANOVA}
model_lm <- 
  lm(ter ~ system, data = data_ter_mean)

summary(model_lm)
```


```{r present model matrix to show dummy coding}
model.matrix(model_lm) %>% unique()
```


```{r conduct significance test}
model_parameters(anova(model_lm, test = "Chisq"))
```


#A smarter way to model and analyze the evaluation data

```{r model data via LMEM to account for repeated measurements on the same sentence}
model_lmm <- 
  lmer(ter ~ system + (1 | sentence_id), data = data_ter)

summary(model_lmm)
```


```{r LMEM omnibus test}
anova(model_lmm, lmer.df = "asymptotic", test= "Chisq")
```


```{r reconstruct group means and differences plus test}
group_means <- 
  emmeans(object  = model_lmm, 
          specs   = pairwise ~ system, 
          lmer.df = "asymptotic")

group_means
```


## Is the Performance Gain from Feedback Uniform for all Sentences?
```{r kreutzer_sig_fig2, echo=FALSE, message=FALSE, fig.height = 3.9, fig.width = 8.3, fig.align = "center"}
ggplot(data = data_ter, 
       aes(x = src_length, y = ter, colour = system)) +
  theme_bw()+
  theme(legend.position = 'none') +
  facet_wrap(~system) +
  xlab("Source Sentence Length") +
  ylab("TER Score") +
  geom_point(aes(colour = system), alpha = .1) + #add points
  geom_vline(xintercept = c(15, 55), linetype = "dashed") +
  geom_density_2d(alpha = .3) +                  #add contour lines
  geom_smooth(method = "loess", se = FALSE)      #add loess smoother
  #geom_smooth(method = "gam", se = FALSE)       #alternative: gam smoother
```


```{r classify sentences by length}
data_ter_mean %<>%
  mutate(src_length_class = factor((src_length > 15) + (src_length > 55), 
                                   levels = 0:2, 
                                   labels = c("short", "typical", "very long"))) 

data_ter %<>%
  mutate(src_length_class = factor((src_length > 15) + (src_length > 55), 
                                   levels = 0:2, 
                                   labels = c("short", "typical", "very long"))) 
```

```{r kreutzer_sig_fig3, fig.height = 3.9, fig.width = 8.3, fig.align = "center"}
data_plot <-  data_ter

levels(data_plot$src_length_class) <- 
glue("{levels(data_plot$src_length_class)} (#sentences={table(data_ter_mean$src_length_class) / 3})")


ggplot(data = data_plot) +
  theme_bw() +
  theme(legend.position = "none") +
  xlab("") +
  ylab("TER Score") +
  geom_boxplot(aes(x = src_length_class, y = ter, fill = system), alpha = .3)
```


```{r LMEM with system/input length interaction as fixed effect, warning=FALSE}
model_ssl <- 
  #formula expands to:
  #ter ~ system + src_length_class + system:src_length_class + (1 | sentence_id)
  lmer(ter ~ system*src_length_class + (1 | sentence_id), data = data_ter)
```


```{r omnibus test for interaction model}
anova(model_ssl, lmer.df = "asymptotic")
```


```{r calc group means investige interaction}
group_means_ssl <- 
  emmeans(model_ssl, ~ system:src_length_class, lmer.df = "asymptotic")
```


```{r kreutzer_sig_fig4, echo=FALSE, fig.height = 3.9, fig.width = 8.3, fig.align = "center"}
ggplot(as_tibble(group_means_ssl)) +
  theme_bw() +
  theme(legend.position = c(0.1,.8)) +
  xlab("Source Sentence Length (grouped)") +
  ylab("Estimated Group Mean") + 
  geom_pointrange(aes(x = src_length_class, 
                      y = emmean,
                      ymin = emmean - SE,
                      ymax = emmean + SE,
                      colour = system),
                  alpha = .7) +
  geom_line(aes(x = src_length_class,
                y = emmean,
                group = system,
                colour = system), 
            alpha = .3)
```


```{r conduct post hoc test}
emmeans(object = model_ssl, 
        specs  = pairwise ~ system | src_length_class, 
        lmer.df = "asymptotic")$contrasts #..$contrasts to just print the contrasts
```